---
openapi: 3.0.1
info:
  title: API V1
  version: v1
paths:
  "/products":
    get:
      summary: List all products
      tags:
      - Products
      responses:
        '200':
          description: success
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    id:
                      type: integer
                    name:
                      type: string
                    quantity:
                      type: integer
                    price:
                      type: number
                      format: float
                    created_at:
                      type: string
                    updated_at:
                      type: string
                  required:
                  - id
                  - name
                  - quantity
                  - price
    post:
      summary: Create a product
      tags:
      - Products
      parameters: []
      responses:
        '201':
          description: created
        '422':
          description: unprocessable entity
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                quantity:
                  type: integer
                price:
                  type: number
                  format: float
              required:
              - name
              - quantity
              - price
  "/products/{id}":
    get:
      summary: Get a product by id
      tags:
      - Products
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: integer
      responses:
        '200':
          description: success
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: integer
                  name:
                    type: string
                  quantity:
                    type: integer
                  price:
                    type: number
                    format: float
                required:
                - id
                - name
                - quantity
                - price
        '404':
          description: not found
    put:
      summary: Update product
      tags:
      - Products
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: integer
      responses:
        '200':
          description: success
        '404':
          description: not found
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                quantity:
                  type: integer
                price:
                  type: number
                  format: float
              required:
              - name
              - quantity
              - price
    delete:
      summary: Delete a product
      tags:
      - Products
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: integer
      responses:
        '204':
          description: no content
        '404':
          description: not found
servers:
- url: http://localhost:3000  

