default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: product_inventory_development
  username: postgres
  password: postgres

test:
  <<: *default
  database: product_inventory_test
  username: postgres
  password: postgres
